### ISSUE TITLE
Started to get "Could not find node with given id"

### ISSUE THREAD

**Issue by gajus** [gwuhaolin/chrome-render#8]
Started to get this error. No clear context/ reason.

```
{ method: 'Page.enable', params: undefined }
{ method: 'DOM.enable', params: undefined }
{ method: 'Network.enable', params: undefined }
{ method: 'Console.enable', params: undefined }
{ method: 'Network.setCookie',
  params:
   { url: 'https://go2cinema.com/movies/my-cousin-rachel-2017-3128208',
     name: 'GO2CINEMA_RENDERER',
     value: '1' } }
{ method: 'Page.addScriptToEvaluateOnLoad',
  params: { scriptSource: '\nObject.defineProperty(window, \'isPageReady\', {\n  set: function() { console.log(\'P_R\'); },\n})' } }
{ method: 'Network.setExtraHTTPHeaders',
  params: { headers: { 'x-chrome-render': '1.2.0' } } }
{ method: 'Emulation.setDeviceMetricsOverride',
  params:
   { deviceScaleFactor: 1,
     fitWindow: false,
     height: 1080,
     mobile: false,
     width: 1920 } }
{ method: 'Page.navigate',
  params:
   { url: 'https://go2cinema.com/movies/my-cousin-rachel-2017-3128208',
     referrer: undefined } }
{ method: 'DOM.getDocument', params: undefined }
{ method: 'DOM.getDocument', params: undefined }
{ method: 'DOM.getOuterHTML', params: { nodeId: 1 } }
{ method: 'DOM.getOuterHTML', params: { nodeId: 5 } }
error true { code: -32000, message: 'Could not find node with given id' }
{ method: 'Page.navigate', params: { url: 'about:blank' } }
/Users/gajus/Documents/dev/applaudience/go2cinema-com-renderer/src/bin/index.js:15
  throw error;
  ^

Error: Could not find node with given id
    at /Users/gajus/Documents/dev/applaudience/go2cinema-com-renderer/node_modules/chrome-remote-interface/lib/chrome.js:83:28
    at Chrome.handleMessage (/Users/gajus/Documents/dev/applaudience/go2cinema-com-renderer/node_modules/chrome-remote-interface/lib/chrome.js:273:13)
    at WebSocket.<anonymous> (/Users/gajus/Documents/dev/applaudience/go2cinema-com-renderer/node_modules/chrome-remote-interface/lib/chrome.js:250:27)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver._receiver.onmessage (/Users/gajus/Documents/dev/applaudience/go2cinema-com-renderer/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/Users/gajus/Documents/dev/applaudience/go2cinema-com-renderer/node_modules/ws/lib/Receiver.js:385:14)
    at extension.decompress (/Users/gajus/Documents/dev/applaudience/go2cinema-com-renderer/node_modules/ws/lib/Receiver.js:354:40)
    at _inflate.flush (/Users/gajus/Documents/dev/applaudience/go2cinema-com-renderer/node_modules/ws/lib/PerMessageDeflate.js:279:12)
    at afterWrite (_stream_writable.js:430:3)
    at onwrite (_stream_writable.js:421:7)
    at afterTransform (_stream_transform.js:102:3)
    at TransformState.afterTransform (_stream_transform.js:75:12)
    at Zlib.callback (zlib.js:471:7)

```

**Comment by gajus** [comment]
For whatever reason the page is getting redirected to `about:blank` is what seems to be causing the error.

**Comment by gajus** [comment]
Hah, found it...

Turns out that I was setting `window.isPageReady = 1;` twice and `chrome-render` does not like that.

Based on this:

```js
scriptSource: '\nObject.defineProperty(window, \'isPageReady\', {\n  set: function() { console.log(\'P_R\'); },\n})' }

```

I am going to guess that setting the value twice triggers `P_R` message twice which breaks whatever internal `chrome-render` logic.

Fair enough – does not make sense to set `window.isReadyPage` twice. However, a more user friendly error is needed.

**Comment by gwuhaolin** [comment]
fixed in https://github.com/gwuhaolin/chrome-render/commit/6b97da9b806e5eec766120aa4fe2c010221c87dd
Add a `hasReturn` flag to avoid resolve multi times. Now only the first `window.isPageReady = 1` will lead to read DOM and return.

**Comment by gajus** [comment]
I moved to a different project as I had other lower-level features that I need supporting, https://github.com/gajus/usus. Thank you for the support.

**Comment by SkeLLLa** [comment]
@gwuhaolin I have the same error message, but I  don't set isReady multiple times.
Here's stack trace of error:
```
"[
{
  "file": "/my-project/node_modules/chrome-remote-interface/lib/chrome.js",
  "methodName": "<unknown>",
  "lineNumber": 90,
  "column": 30
},
{
  "file": "/my-project/node_modules/chrome-remote-interface/lib/chrome.js",
  "methodName": "Chrome.handleMessage",
  "lineNumber": 289,
  "column": 13
},
{
  "file": "/my-project/node_modules/chrome-remote-interface/lib/chrome.js",
  "methodName": "WebSocket.<anonymous>",
  "lineNumber": 266,
  "column": 27
},
{
  "file": "events.js",
  "methodName": "emitTwo",
  "lineNumber": 125,
  "column": 13
},
{
  "file": "events.js",
  "methodName": "WebSocket.emit",
  "lineNumber": 213,
  "column": 7
},
{
  "file": "/my-project/node_modules/ws/lib/WebSocket.js",
  "methodName": "Receiver._receiver.onmessage",
  "lineNumber": 143,
  "column": 54
},
{
  "file": "/my-project/node_modules/ws/lib/Receiver.js",
  "methodName": "Receiver.dataMessage",
  "lineNumber": 385,
  "column": 14
},
{
  "file": "/my-project/node_modules/ws/lib/Receiver.js",
  "methodName": "extension.decompress",
  "lineNumber": 354,
  "column": 40
},
{
  "file": "/my-project/node_modules/ws/lib/PerMessageDeflate.js",
  "methodName": "_inflate.flush",
  "lineNumber": 279,
  "column": 12
},
{
  "file": "_stream_writable.js",
  "methodName": "afterWrite",
  "lineNumber": 438,
  "column": 3
},
{
  "file": "_stream_writable.js",
  "methodName": "onwrite",
  "lineNumber": 429,
  "column": 7
}
]"
```

**Comment by gwuhaolin** [comment]
@SkeLLLa 
Your stack trace of error are all in `chrome-remote-interface` which is a dependent of chrome-render.
From your stack trace of error I can't get useful info.

I guess you use  `useReady` in wrong way, you should use it in this way
`useReady`: `boolean` whether use `window.isPageReady=1` to notify chrome-render page has ready. default is `false` chrome-render use `domContentEventFired` as page has ready.
```js
  it('#render() inject script', async function () {
    const chromeRender = await ChromeRender.new();
    const html = await chromeRender.render({
      url: 'https://bing.com',
      useReady: true,
      script: `window.isPageReady=1;`,
    });
    // console.log(html);
    await chromeRender.destroyRender();
  });
```

**Comment by SkeLLLa** [comment]
@gwuhaolin I use `window.isPageReady=1` just as in your example above, but with little difference:
```
const chromeRender = await ChromeRender.new();
    const html = await chromeRender.render({
      url: 'https://bing.com',
      useReady: true,
      script: `setTimeout(() => {window.isPageReady=1;}, 5000)`,
    });
```

Should I destroy render after each page rendered?

And the case is that some pages are rendered well, but other pages throw an error I've mentioned above.

**Comment by gwuhaolin** [comment]
@SkeLLLa 
chrome-render will reuse opened tabs to improve performance and reduce resource use ([chrome-pool](https://github.com/gwuhaolin/chrome-pool)), you shouldn't destroy render after each page rendered, your should destroy render when you don't need render anymore.

**Comment by SkeLLLa** [comment]
@gwuhaolin Then I understood correctly. But anyway I can't understand why that error happen. I've tried another lib (usus) built on chrome remote interface and it works on that pages well.

Any suggestions where should I look (I mean place some breakpoints) to be able to see where exactly and why that errors happen?

**Comment by gwuhaolin** [comment]
It same to be a chrome-render bug, I will test your case and fix it later.

**Comment by SkeLLLa** [comment]
@gwuhaolin here's simple test-case to reproduce the bug:
```js
it('#render() nodeid bug', async function () {
    const chromeRender = await ChromeRender.new({
      maxTab: 8
    });
    const a = await chromeRender.render({
      url: 'https://gwuhaolin.github.io/redemo/',
      useReady: true,
      script: `setTimeout(function(){window.isPageReady = 1;}, 1000);`,
      renderTimeout: 5000
    });

    const b = await chromeRender.render({
      url: 'https://gwuhaolin.github.io/redemo/',
      useReady: true,
      script: `setTimeout(function(){window.isPageReady = 1;}, 1000);`,
      renderTimeout: 5000
    });
    await chromeRender.destroyRender();
  });
```

**Comment by SkeLLLa** [comment]
I've tried another thing:
```
const dom = await DOM.getDocument();
console.log('nodeid', dom.root.nodeId); // returns 6 on second render
console.log(await DOM.getOuterHTML({ nodeId: 1 })); // returns proper html
const ret = await DOM.getOuterHTML({ nodeId: dom.root.nodeId }); // produces error
```

**Comment by SkeLLLa** [comment]
Another investigation showed that there's a difference between 1st and 2nd:
```
{
  "nodeId": 1,
  "backendNodeId": 3,
  "nodeType": 9,
  "nodeName": "#document",
  "localName": "",
  "nodeValue": "",
  "childNodeCount": 2,
  "children": [
    {
      "nodeId": 2,
      "parentId": 1,
      "backendNodeId": 4,
      "nodeType": 10,
      "nodeName": "html",
      "localName": "",
      "nodeValue": "",
      "publicId": "",
      "systemId": ""
    },
    {
      "nodeId": 3,
      "parentId": 1,
      "backendNodeId": 5,
      "nodeType": 1,
      "nodeName": "HTML",
      "localName": "html",
      "nodeValue": "",
      "childNodeCount": 2,
      "children": [
        {
          "nodeId": 4,
          "parentId": 3,
          "backendNodeId": 6,
          "nodeType": 1,
          "nodeName": "HEAD",
          "localName": "head",
          "nodeValue": "",
          "childNodeCount": 14,
          "attributes": []
        },
        {
          "nodeId": 5,
          "parentId": 3,
          "backendNodeId": 7,
          "nodeType": 1,
          "nodeName": "BODY",
          "localName": "body",
          "nodeValue": "",
          "childNodeCount": 4,
          "attributes": []
        }
      ],
      "attributes": [
        "lang",
        "zh-cn"
      ],
      "frameId": "16038.1"
    }
  ],
  "documentURL": "https://gwuhaolin.github.io/redemo/",
  "baseURL": "https://gwuhaolin.github.io/redemo/",
  "xmlVersion": ""
}
```

2nd:
```
{
  "nodeId": 6,
  "backendNodeId": 8,
  "nodeType": 9,
  "nodeName": "#document",
  "localName": "",
  "nodeValue": "",
  "childNodeCount": 1,
  "children": [
    {
      "nodeId": 7,
      "parentId": 6,
      "backendNodeId": 9,
      "nodeType": 1,
      "nodeName": "HTML",
      "localName": "html",
      "nodeValue": "",
      "childNodeCount": 2,
      "children": [
        {
          "nodeId": 8,
          "parentId": 7,
          "backendNodeId": 10,
          "nodeType": 1,
          "nodeName": "HEAD",
          "localName": "head",
          "nodeValue": "",
          "childNodeCount": 0,
          "attributes": []
        },
        {
          "nodeId": 9,
          "parentId": 7,
          "backendNodeId": 11,
          "nodeType": 1,
          "nodeName": "BODY",
          "localName": "body",
          "nodeValue": "",
          "childNodeCount": 0,
          "attributes": []
        }
      ],
      "attributes": [],
      "frameId": "16038.1"
    }
  ],
  "documentURL": "about:blank",
  "baseURL": "about:blank",
  "xmlVersion": ""
}
```

As you can see it seems that while chrome tab is released in `chrome-pool` it's url is set to `about:blank` and for some reason it renders it instead of desired url.

**Comment by SkeLLLa** [comment]
@gwuhaolin It seems I've found a bug. 
Method ` tab.protocol.Page.navigate({ url: 'about:blank' });` is async and returns promise. But it's not awaited anywhere. Also release method isn't async as well. 

I'll make PR to chrome-render and chrome-pool.

**Comment by gwuhaolin** [comment]
fixed in https://github.com/gwuhaolin/chrome-render/issues/13
